apiVersion: v1
kind: Service
metadata:
  name: {{ include "ns.fullname" . }}-svc-stateful
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: {{ include "ns.fullname" . }}-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ns.fullname" . }}-statefulset
spec:
  selector:
    matchLabels:
      app: {{ include "ns.fullname" . }}-statefulset # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: {{ include "ns.fullname" . }}-statefulset # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        #image: k8s.gcr.io/nginx-slim:0.8
        image: "{{ .Values.ns.statefulSetImage.name }}:{{ .Values.ns.statefulSetImage.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www-ns
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www-ns
        hostPath:
          path: /tmp/ikhostpath-ns/
